apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: beobzwwhi-go 
  janus-idp.io/tekton: beobzwwhi-go
  backstage.io/kubernetes-id: beobzwwhi-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: beobzwwhi-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  