apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: beobzwwhi-go-gitops
  description: This is GitOps manifest for beobzwwhi-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: beobzwwhi-go
    backstage.io/kubernetes-id: beobzwwhi-go 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: beobzwwhi-go-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:beobzwwhi-go
