apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: beobzwwhi-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: beobzwwhi-go 
  name: beobzwwhi-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: beobzwwhi-go 
